defaults:
    - _self_
    - environment@host: manivald  # Options: lumi, manivald
    - datasets@dataset: FCC  # Options: FCC, CEPC
    - models@model: one_step  # TODO: Does it work?
    - preprocessing
    - training