training:
    output_dir: null
    dataloader:
        batch_size:
            one_step: 128
            two_step: 512
        num_dataloader_workers: 2
        prefetch_factor: 100
    trainer:
        max_epochs: 5 # 50 epochs in Guang paper
    model_evaluation_only: False
defaults:
    - _self_
    - models: models

hydra:
    output_subdir: null
    run:
        dir: .