training:
    output_dir: /home/laurits/tmp/training1
    batch_size: 8192
    num_dataloader_workers: 2
    prefetch_factor: 100
    trainer:
        max_epochs: 5
    data:
        fraction_valid: 0.2

defaults:
    - _self_
    - datasets: datasets
    - models: models
