training:
    debug_run: false
    type: one_step  # Options: one_step, two_step, two_step_minimal
    output_dir: null
    output_dir_: ${training.output_dir}/${training.type}
    models_dir: ${training.output_dir_}/models
    log_dir: ${training.output_dir_}/logs
    predictions_dir: ${training.output_dir_}/predictions
    results_dir: ${training.output_dir}/results
    dataloader:
        batch_sizes:
            one_step: 128
            two_step: 512
            two_step_minimal: 512
        batch_size: ${training.dataloader.batch_sizes[${training.type}]}
        num_dataloader_workers: 1
        prefetch_factor: 100
    trainer:
        max_epochs: 250 # 50 epochs in Guang paper
    model_evaluation_only: False

hydra:
    output_subdir: null
    run:
        dir: .