training:
    output_dir: /home/laurits/ml4cc/training-outputs/20241214_150Epoch_SDG_LSTM
    batch_size: 8192
    num_dataloader_workers: 2
    prefetch_factor: 100
    trainer:
        max_epochs: 150 # 50 epochs in Guang paper
    data:
        fraction_valid: 0.2

defaults:
    - _self_
    - datasets: datasets
    - models: models
