training:
    output_dir: /home/laurits/ml4cc/training-outputs/20241219_150Epoch_AdamW_LSTM
    batch_size: 8192
    num_dataloader_workers: 2
    prefetch_factor: 100
    trainer:
        max_epochs: 150 # 50 epochs in Guang paper
    data:
        fraction_valid: 0.2
        dataset: FCC
model_evaluation_only: False
checkpoints:
    peakFinding:
        LSTM:
            model: /home/laurits/ml4cc/training-outputs/20241214_150Epoch_LSTM/models/best_model.ckpt
            losses: /home/laurits/ml4cc/training-outputs/20241214_150Epoch_LSTM/logs/peakFinding/version_0/metrics.csv
defaults:
    - _self_
    - datasets: datasets
    - models: models
