_target_: ml4cc.models.simpler_models.DNNModule
name: CNN
hyperparameters:
    conv_layer_1:
        in_channels: 1
        out_channels: 32
        kernel_size: 4
    pool_layer_1:
        kernel_size: 2
    conv_layer_2:
        out_channels: 16
        kernel_size: 4
    linear_layer_1:
        # in_features: ???
        out_features: 32
    output_layer:
        in_features: 32
        out_features: 1
    num_features: 3000  # TODO: Fix - should this be the one-step style?
optimizer:
    target: torch.optim.AdamW
    lr: 0.001

checkpoint:
    model: null
    losses: null
