_target_: ml4cc.models.DGCNN.DGCNN
name: DGCNN
optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    params: null
hyperparameters:
    n_conv1: 32
    n_conv2: 32
    n_conv3: 64
    n_mlp1: 264
    n_mlp2: 264
    n_mlp3: 264
    aggr: max
    step: 10
    gamma: 0.5
    k: 4
    mlp_dropout: 0.5
    out_channels: 2

checkpoint:
    model: null
    losses: null
