_target_: ml4cc.models.transformer.TransformerModule
name: transformer
hyperparameters:
    input_dim: 15 # Actually this should be 1 or 15.
    d_model: 256 # 512
    num_heads: 8
    num_layers: 4 # 3
    hidden_dim: 512 # 2048
    num_classes: 1
    max_len: ${dataset.input_dim} # Maybe ${dataset.max_peak_cands}
    lr: 1e-6
    dropout: 0.05
checkpoint:
    model: null
    losses: null
