name: lumi
project_dir: /scratch/project_465001293/ML4CC/ml4cc
data_dir: /scratch/project_465001293/ML4CC/data
slurm:
  queue:
    preprocessing:
      partition: small
      time: 02:00:00
      cpus: 1
      mem: 4G

