name: manivald
home_dir: /home/laurits/
project_dir: ${home_dir}/ml4cc
data_dir: /scratch/persistent/laurits/ml4cc/
slurm:
  queue:
    ntupelizer:
      partition: short
      time: 02:00:00
      cpus: 1
      mem: 4G