CEPC:
  preprocessing:
    branches: null
    branches_to_create:
      - EventNo
      - ID
      - Shift
      - Sigma
      - Time
    tree_path: sim
    training_types:
      - clusterization
      - peakFinding
    particle_types:
      - kaon
      - pion
    raw_input_dir: /home/laurits/ml4cc/ml4cc/data/CEPC/data/

