CEPC:
    preprocessing:
        branches: null
        tree_path: sim
        training_types:
            - clusterization
            - peakFinding
        particle_types:
            - kaon
            - pion
        raw_input_dir: /scratch/persistent/laurits/ml4cc/CEPC/data/
        slurm:
            use_it: False
            slurm_run: False
            files_per_job: 1
            input_path: null
    data_dir: /scratch/project_465001293/ML4CC/data/CEPC/preprocessed_data/
    # data_dir: /scratch/persistent/laurits/ml4cc/CEPC/preprocessed_data/
    row_group_size: 1024
    slidig_window:
        size: 15
        stride: 15
