name: FCC
input_dim: 1200
branches: null
tree_path: sim
training_types:
    - clusterization
    - peakFinding
particle_types:
    - muon
raw_input_dir: ${host.data_dir}/FCC/data/
data_dir: ${host.data_dir}/FCC/preprocessed_data/
