FCC:
    input_dim: 1200
    preprocessing:
        branches: null
        tree_path: sim
        training_types:
            - clusterization
            - peakFinding
        particle_types:
            - muon
    data_dir: ${host.data_dir}/FCC/preprocessed_data/
    raw_input_dir: ${host.data_dir}/FCC/raw_data/
